#!/bin/bash -e

# delete old bundle images
IMGRX="/[a-z0-9]{32}.png"
find ../ -type f -maxdepth 2 | egrep $IMGRX | xargs rm

# generate bundle
npm run build

# copy new bundle images
find . -type f -maxdepth 1 | egrep $IMGRX | xargs -I{} cp {} ../

# copy files
cp bundle.js ../
cp index.html ../
cp 404.html ../

# copy assets
rm -rf ../assets
mkdir ../assets
cp -rf assets/dist ../assets

# update github
git add ../
git commit -m "Updating site"
git push
