#!/bin/bash -e

# generate bundle
npm run build

# copy files
cp bundle.js ../
cp index.html ../
cp 404.html ../

# copy assets
rm -rf ../assets
mkdir ../assets
cp -rf assets/dist ../assets

# copy bundle images
find . -type f -maxdepth 1 | egrep "/[a-z0-9]{32}.png" | xargs -I{} cp {} ../

# update github
git add ../
git commit -m "Updating site"
git push
